ScienceCenter/ScienceCenter/Models/Class.cs
namespace ScienceCenter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            SignIns = new HashSet<SignIn>();
            StudentClasses = new HashSet<StudentClass>();
        }

        public int ClassID { get; set; }

        public int? CRN { get; set; }

        [Required]
        [StringLength(10)]
        public string DeptPrefix { get; set; }

        [Required]
        [StringLength(4)]
        public string ClassNum { get; set; }

        [Required]
        public string Instructor { get; set; }

        [StringLength(10)]
        public string Days { get; set; }

        [StringLength(25)]
        public string Time { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SignIn> SignIns { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}

ScienceCenter/ScienceCenter/Models/ViewModels/Data.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ScienceCenter.Models.ViewModels
{
    public class Data
    {
        [Display(Name = "Week")]
        public int Week { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }

        [Display(Name = "Hour")]
        public int Hour { get; set; }

        [Display(Name = "Minute")]
        public int Min { get; set; }

        [Display(Name = "Second")]
        public int Sec { get; set; }

        [StringLength(8)]
        [Display(Name = "V-Number")]
        public string VNum { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "CRN")]
        public int? CRN { get; set; }

        [StringLength(10)]
        [Display(Name = "Class Prefix")]
        public string DeptPrefix { get; set; }

        [Display(Name = "Class Number")]
        public string ClassNum { get; set; }

        [Display(Name = "Instructor")]
        public string Instructor { get; set; }

        [StringLength(10)]
        [Display(Name = "Days")]
        public string Days { get; set; }

        [StringLength(25)]
        [Display(Name = "Start Time")]
        public string StartTime { get; set; }
    }
}

ScienceCenter/ScienceCenter/Models/ViewModels/ProfData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ScienceCenter.Models.ViewModels
{
    public class ProfData
    {
        [Key]
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "CRN")]
        public int? CRN { get; set; }

        [StringLength(10)]
        [Display(Name = "Class Prefix")]
        public string DeptPrefix { get; set; }

        [Display(Name = "Class Number")]
        public string ClassNum { get; set; }

        [Display(Name = "Instructor")]
        public string Instructor { get; set; }

        [StringLength(10)]
        [Display(Name = "Days")]
        public string Days { get; set; }

        [StringLength(25)]
        [Display(Name = "Start Time")]
        public string StartTime { get; set; }

        [Display(Name = "Times Came In")]
        public int TimesIn { get; set; }
    }
}

ScienceCenter/ScienceCenter/Controllers/FacultyController.cs
using OfficeOpenXml;
using ScienceCenter.Excel;
using ScienceCenter.Models;
using ScienceCenter.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScienceCenter.Controllers
{
    public class FacultyController : Controller
    {
        //Database Connection
        private readonly ScienceContext db = new ScienceContext();

        /*
         * This method returns a welcome page for Faculty users.
         */
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(int? download)
        {
            //if you press the download button, the excel sheet will be created.
            if (download == 1)
            {
                EntireExcel();
            }
            //If you press the reset button, it will redirect you to another page.
            if (download == 2)
            {
                return RedirectToAction("Reset");
            }
            //If you press the Go Back Button, it will redirect you to another page.
            if (download == 3)
            {
                return RedirectToAction("Index", "Home");
            }
            //If you press the download by professor button, the excel sheet for it will be created.
            if(download == 4)
            {
                ProfExcel();
            }
            //If you press the download by class button, the excel sheet for it will be created.
            if(download == 5)
            {
                ClassExcel();
            }
            if(download >= 6)
            {
                int num = (int)download - 5;
                return RedirectToAction("Extra", new { num });
            }
            return View();
        }

        /*
         * This method will do the work of downloading the excel file with 'hopefully'
         * all the data.
         */
        private void EntireExcel()
        {
            DataExcel excel = new DataExcel();
            Response.ClearContent();
            Response.BinaryWrite(excel.GenerateExcel(GetData()));
            Response.AddHeader("content-disposition", "attachment; filename=ScienceCenterData.xlsx");
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.Flush();
            Response.End();
        }

        /*
         * This method creates and downloads the Sort by Professor excel sheet.
         */ 
         private void ProfExcel()
        {
            ProfessorExcel excel = new ProfessorExcel();
            Response.ClearContent();
            Response.BinaryWrite(excel.GenerateExcel(GetProfData()));
            Response.AddHeader("content-disposition", "attachment; filename=ScienceCenterDataByProf.xlsx");
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.Flush();
            Response.End();
        }

        /*
         * This method creates and downloads the Sort by Class Level excel sheet.
         */
        private void ClassExcel()
        {
            ClassLevelExcel excel = new ClassLevelExcel();
            Response.ClearContent();
            Response.BinaryWrite(excel.GenerateExcel(GetClassData()));
            Response.AddHeader("content-disposition", "attachment; filename=ScienceCenterDataByClass.xlsx");
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.Flush();
            Response.End();
        }

        /*
         * This method gets all of the data for the "Data Excel"
         */
        private List<Data> GetData()
        {
            //Create an empty list.
            List<Data> datas = new List<Data>();

            //Go through the list of sign ins and add all the data to the list.
            foreach (var SignIn in db.SignIns.ToList())
            {
                Data data = new Data { Week = SignIn.Week, Date = SignIn.Date, Hour = SignIn.Hour, Min = SignIn.Min, VNum = SignIn.Student.VNum, FirstName = SignIn.Student.FirstName, LastName = SignIn.Student.LastName, CRN = SignIn.Class.CRN, DeptPrefix = SignIn.Class.DeptPrefix, ClassNum = SignIn.Class.ClassNum, Days = SignIn.Class.Days, Instructor = SignIn.Class.Instructor, StartTime = SignIn.Class.Time };

                datas.Add(data);
            }

            //Remove the Placeholder class.
            var remClass = datas.Where(d => d.CRN == 0).Select(d => d).FirstOrDefault();
            datas.Remove(remClass);

            //Return the list of the data.
            return datas;
        }

        /*
         * This method gets all the data in no particular order for the 2 extra excel sheets.
         */
        private List<ProfData> GetProfs()
        {
            //Create an empty list to be filled after the queries.
            List<ProfData> pData = new List<ProfData>();

            //Going through all the studentClasses so we don't 'double' count
            foreach(var studentClass in db.StudentClasses.ToList())
            {
                int numTimes = db.SignIns
                    .Where(s => s.StudentID == studentClass.VNum)
                    .Where(s => s.ClassId == studentClass.ClassId)
                    .Count();

                //make sure we have at least 1
                if (numTimes != 0)
                {
                    //Get the student and the class
                    Student student = studentClass.Student;
                    Class @class = studentClass.Class;

                    //set the data
                    ProfData data = new ProfData { FirstName = student.FirstName, LastName = student.LastName, CRN = @class.CRN, DeptPrefix = @class.DeptPrefix, Instructor = @class.Instructor, Days = @class.Days, ClassNum = @class.ClassNum, StartTime = @class.Time, TimesIn = numTimes };

                    //add it to the list
                    pData.Add(data);
                }
            }

            //return the created list.
            return pData;
        }


    /*
     * This method gets all the ProfData for the "Prof" excel sheet
     */
        private List<ProfData> GetProfData()
        {
            //Create the list.
            List<ProfData> pData = GetProfs();

            //Sort the list by instructor
            pData = pData.OrderBy(p => p.Instructor).ToList();

            //return the ordered list.
            return pData;
        }

        /*
         * This method gets all the ClassData for the "Class Level" excel sheet
         */
        private List<ProfData> GetClassData()
        {
            //Create the list.
            List<ProfData> pData = GetProfs();

            //Sort the list by instructor
            pData = pData
                .OrderBy(p => p.DeptPrefix)
                .OrderBy(p => p.ClassNum)
                .ToList();

            //return the ordered list.
            return pData;
        }

        /*
        * This method returns a table with all of the data from the Database.
        */
        [HttpGet]
        public ActionResult Data()
        {
            return View(db.SignIns.ToList());
        }

        /*
        * This method returns a table with all of the data sorted by professor from the 
        * Database.
        */
        [HttpGet]
        public ActionResult ProfData()
        {
            return View(GetProfData());
        }

        /*
        * This method returns a table with all of the data sorted by class level from the 
        * Database.
        */
        [HttpGet]
        public ActionResult ClassData()
        {
            return View(GetClassData());
        }

        /*
         * This method returns a page with a box where users can add classes to the database.
         * It will allow users to add classes whenever they want to and will always have the 
         * placeholder class automatically get added to the db.
         */
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    Stream fs = file.InputStream;
                    ExcelPackage package = new ExcelPackage(fs);
                    foreach (ExcelWorksheet worksheet in package.Workbook.Worksheets)
                    {
                        Class @class = new Models.Class();
                        for (int i = worksheet.Dimension.Start.Row + 1; i <= worksheet.Dimension.End.Row; i++)
                        {
                            if (Int32.Parse(worksheet.Cells[i, 1].Value.ToString()) != 0)
                            {
                                @class.CRN = Int32.Parse(worksheet.Cells[i, 1].Value.ToString());
                                @class.DeptPrefix = worksheet.Cells[i, 2].Value.ToString();
                                @class.ClassNum = worksheet.Cells[i, 3].Value.ToString();
                                @class.Time = worksheet.Cells[i, 4].Value.ToString();
                                @class.Days = worksheet.Cells[i, 5].Value.ToString();
                                @class.Instructor = worksheet.Cells[i, 6].Value.ToString();
                                db.Classes.Add(@class);
                                db.SaveChanges();
                            }                            
                        }
                    }
                    return RedirectToAction("Class");
                }
                else
                {
                    ViewBag.Error = "The file you uploaded has no data in it, please upload another one."; //return error message
                    return View();
                }
            }

ScienceCenter/ScienceCenter/Views/Faculty/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<div class="container">
    <div class="center">
        <h1>Add classes for the current term here!</h1>
        <h3 style="margin-bottom:25px;">Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
        <h3>The Order of the Data should be:</h3>
        <p>CRN, Class Prefix, Class Number, Start Time (Online), Days, Instructor</p>
    </div>
    <h2>Instructions:</h2>
    <ol>
        <li>Copy and paste class data from WOU RealTime Availability website to Notepad, which is in Accessories (to strip the formatting).</li>
        <li>Copy and paste that data into Excel (Ctrl-A, Ctrl-C). Include a header row</li>
        <li>Remove the unneccesary fields so that it matches the order and columns above.</li>
        <li>For classes that span multiple rows, make it so they are only on one row. (If it has M, W, and TF split up, put them all on the same line.)</li>
        <li>If the class is online, please add "Online" to the Start Time column, you may leave the Days column empty.</li>
        <li>Copy and paste the data from Excel into the text box below.</li>
    </ol>
    <div class="center">
        @using (Html.BeginForm("Add", "Faculty", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <h4>
                @Html.TextBox("file", "", new { type = "file", accept = ".xlsx, .xls, .csv" })
            </h4>
            <h3>
                <button class="btn" type="submit">Submit</button>
            </h3>
        }
    </div>
</div>

ScienceCenter/ScienceCenter/Views/Faculty/Class.cshtml
@model IEnumerable<ScienceCenter.Models.Class>

@{
    ViewBag.Title = "Class";
}

<div class="container">
    <div class="center">
        <h1>Here is a table with all of the classes found on the site</h1>
        <h3>Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
    </div>
</div>
<br /><br />
<table align="center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CRN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeptPrefix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Days)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CRN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeptPrefix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Instructor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Days)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
        </tr>
    }

</table>

ScienceCenter/ScienceCenter/Views/Faculty/ClassData.cshtml
@model IEnumerable<ScienceCenter.Models.ViewModels.ProfData>

@{
    ViewBag.Title = "ClassData";
}

<div class="container">
    <div class="center">
        <h1>Here is all of the data from the Science Center sign in sorted by class level</h1>
        <h3>Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
    </div>
</div>
<br /><br />
<table align="center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeptPrefix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CRN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Days)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimesIn)
        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DeptPrefix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClassNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CRN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Instructor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Days)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimesIn)
        </td>
    </tr>
    }
</table>

ScienceCenter/ScienceCenter/Views/Faculty/Complete.cshtml
@{
    ViewBag.Title = "Complete";
}

<div class="container">
    <div class="center">
        <h1>Your Reset is Complete.</h1>
        <h2>Go Back?: @Html.ActionLink("Back To Home", "Index", "Faculty")</h2>
    </div>
</div>

ScienceCenter/ScienceCenter/Views/Faculty/Data.cshtml
@model IEnumerable<ScienceCenter.Models.SignIn>

@{
    ViewBag.Title = "Data";
}

<div class="container">
    <div class="center">
        <h1>Here is all of the data from the Science Center sign in</h1>
        <h3>Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
    </div>
</div>
<br /><br />
<table align="center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Week)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hour)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Min)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.CRN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.DeptPrefix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.ClassNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.Instructor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.Days)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class.Time)
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Week)
            </td>
            <td>
                @item.Date.ToString("d")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Hour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Min)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Student.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.CRN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.DeptPrefix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.ClassNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Instructor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Days)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class.Time)
            </td>
        </tr>
    }
</table>

ScienceCenter/ScienceCenter/Views/Faculty/Extra.cshtml
@model IEnumerable<ScienceCenter.Models.ViewModels.CountDay>

@{
    ViewBag.Title = "Extra";
}

<div class="container">
    <div class="center">
        <h1>Here is the answer to your question</h1>
        <h3>Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
    </div>
</div>
<br /><br />
<table align="center">
    <tr>
        @if (ViewBag.Id == 1)
        {
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumStudents)
            </th>            
        }
        @if (ViewBag.Id == 2)
        {
            <th>
                @Html.DisplayNameFor(model => model.WeekNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumStudents)
            </th>            
        }
        @if (ViewBag.Id == 5)
        {
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hour)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumStudents)
            </th>            
        }
        @if (ViewBag.Id == 4)
        {                  
            <th>
                Average Number of Students Per Day
            </th>            
        }
        @if (ViewBag.Id == 3)
        {
            <th>
                Average Number of Students Per Week
            </th>            
        }
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        @if (ViewBag.Id == 1)
        {
            <td>
                @item.Date.ToString("d")
            </td>
            <td>
                @Html.DisplayFor(model => item.NumStudents)
            </td>
        }
        @if (ViewBag.Id == 2)
        {
            <td>
                @Html.DisplayFor(model => item.WeekNum)
            </td>
            <td>
                @Html.DisplayFor(model => item.NumStudents)
            </td>
        }
        @if (ViewBag.Id == 5)
        {
            <td>
                @item.Date.ToString("d")
            </td>
            <td>
                @Html.DisplayFor(model => item.Hour)
            </td>
            <td>
                @Html.DisplayFor(model => item.NumStudents)
            </td>
        }
        @if (ViewBag.Id == 4)
        {
            <td>
                @Html.DisplayFor(model => item.AverageNum)
            </td>
        }
        @if (ViewBag.Id == 3)
        {            
            <td>
                @Html.DisplayFor(model => item.AverageNum)
            </td>
        }
    </tr>
    }
</table>

ScienceCenter/ScienceCenter/Views/Faculty/Index.cshtml
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="center">
                <h1>Welcome!</h1>
                <hr />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="center">
                <h2>Get Data Tables</h2>
            </div>
            <h3>@Html.ActionLink("Sign In Sheet", "Data", "Faculty")</h3>
            <h3>@Html.ActionLink("Sign In Sorted by Professor", "ProfData", "Faculty")</h3>
            <h3>@Html.ActionLink("Sign In Sorted by Class Level", "ClassData", "Faculty")</h3>
            <h3>@Html.ActionLink("View All Classes", "Class", "Faculty")</h3>
        </div>
        <div class="col-md-4">
            <div class="center">
                <h4>&nbsp;</h4>
                <img src="~/Images/science-rocks.jpg" style="height:200px;" />

            </div>
        </div>
        <form method="post">
            <div class="col-md-4">
                <div class="center">
                    <h2>Download/Add Data</h2>
                </div>
                <button class="btn" name="download" value="1" type="submit">Sign In Sheet</button><br />
                <button class="btn" name="download" value="4" type="submit">Sign In Sorted by Professor</button><br />
                <button class="btn" name="download" value="5" type="submit">Sign In Sorted by Class Level</button><br />
                @Html.ActionLink("Add Classes for New Term", "Add", "Faculty", null, new { @class = "btn" })
            </div>
        </form>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <div class="center">
                <img src="~/Images/science.jpg" style="height:190px;" />
            </div>
        </div>
        <div class="col-md-6">
            <h4 style="margin-top:30px;">@Html.ActionLink("How many students came each day?", "Extra", "Faculty", new { num = 1 }, null)</h4>
            <h4>@Html.ActionLink("How many students came in each week?", "Extra", "Faculty", new { num = 2 }, null)</h4>
            <h4>@Html.ActionLink("What is the average number of students per week?", "Extra", "Faculty", new { num = 3 }, null)</h4>
            <h4>@Html.ActionLink("What is the average number of students per day?", "Extra", "Faculty", new { num = 4 }, null)</h4>
            <h4>@Html.ActionLink("How many students came in each hour of the day?", "Extra", "Faculty", new { num = 5 }, null)</h4>
        </div>
    </div>
    <hr />
    <div class="row">
        <h3>
            This button is to be used at the end of the term to clear the database for the next one. Don't worry,
            it's not a commitment, it will just take you to another page.
        </h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="center">
                <form method="post">
                    <h3>
                        <button class="btn" name="download" value="2" type="submit">Reset the Data</button>
                    </h3>
                </form>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="center">
                <form method="post">
                    <h3>
                        <button class="btn" name="download" value="3" type="submit">Go Back to Sign In</button>
                    </h3>
                </form>
            </div>
        </div>
    </div>
</div>

ScienceCenter/ScienceCenter/Views/Faculty/ProfData.cshtml
@model IEnumerable<ScienceCenter.Models.ViewModels.ProfData>

@{
    ViewBag.Title = "ProfData";
}

<div class="container">
    <div class="center">
        <h1>Here is all of the data from the Science Center sign in by professor</h1>
        <h3>Link to go back: @Html.ActionLink("Go back to home", "Index", "Faculty")</h3>
    </div>
</div>
<br /><br />
<table align="center">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Instructor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CRN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeptPrefix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Days)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimesIn)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Instructor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CRN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeptPrefix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Days)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimesIn)
            </td>
        </tr>
    }
</table>